### ISSUE TITLE
Copenheimer Bot

### ISSUE THREAD

**Issue by KingQwin520** [5cmc/5cmc.github.io#2]
Yo, just wanna ask if you can make the copenheimer bot public release instead of private?

**Comment by DripDemiGod** [comment]
shit ain't happening cuh

**Comment by CxptxnK** [comment]
i talked to them and their not gonna do that
i might start work on a similar bot

**Comment by Elegantbread** [comment]
can you grief my server with the exception that I can show it to you first
Elegentbread395.aternos.me

**Comment by louboecker** [comment]
aternos LMAO

**Comment by nubovik01** [comment]
xD
